name: Mark Stale Issues
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  stale:
    uses: llm-d/llm-d-infra/.github/workflows/reusable-stale.yaml@6c2d2e60e7fee83e2a300688f6d4d7a2339c2d74 # main
    permissions:
      issues: write
      pull-requests: write
