name: Unstale Issues
on:
  issues:
    types: [reopened]
  issue_comment:
    types: [created]

jobs:
  unstale:
    uses: llm-d/llm-d-infra/.github/workflows/reusable-unstale.yaml@6c2d2e60e7fee83e2a300688f6d4d7a2339c2d74 # main
    permissions:
      issues: write
